- hosts: all
  become: yes
  become_user: root
  roles:
    - role: rvm.ruby
      tags: ruby
      rvm1_rubies: ['ruby-2.4.0']
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_user: vagrant
      rvm1_bundler_install: True
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest 
    - name: epel-release
      yum:
        name: epel-release
        state: latest
    - name: rubygems
      yum:
        name: rubygems
        state: latest 
    - name: git
      yum:
        name: git
        state: latest
    - name: ImageMagick
      yum:
        name: ImageMagick
        state: latest
        
